name: Build and Push

env:
  IMAGE_NAME: digitalearthafrica/deafrica-sandox-custom-ui

on:
  pull_request:
  push:
    branches:
      - main
  release:
    types:
      - created

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DEAFRICA_DOCKER_USERNAME }}
          password: ${{ secrets.DEAFRICA_DOCKER_PASSWORD }}

      - name: Get version number for tagging the image
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            TAG=${{ github.sha }}
          else
            git fetch --prune --unshallow 2> /dev/null || true
            TAG=$(git describe --tags)
          fi
          echo "TAG=$TAG" >> $GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ${{ github.event_name == 'pull_request' && format('{0}:{1}', env.IMAGE_NAME, env.TAG) || format('{0}:latest,{0}:{1}', env.IMAGE_NAME, env.TAG) }}